# ░██████╗░██╗░██████╗░░█████╗░░█████╗░██╗░░██╗░█████╗░████████╗
# ██╔════╝░██║██╔════╝░██╔══██╗██╔══██╗██║░░██║██╔══██╗╚══██╔══╝
# ██║░░██╗░██║██║░░██╗░███████║██║░░╚═╝███████║███████║░░░██║░░░
# ██║░░╚██╗██║██║░░╚██╗██╔══██║██║░░██╗██╔══██║██╔══██║░░░██║░░░
# ╚██████╔╝██║╚██████╔╝██║░░██║╚█████╔╝██║░░██║██║░░██║░░░██║░░░
# ░╚═════╝░╚═╝░╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░
#
# /gigachat - перезагрузить плагин (Право на использование: gigachat.command.reload)
#
#
# ESSENTIALS / SUPER_VANISH / CMI
vanish-provider: ESSENTIALS

# Настройка авто-абновлений
updates:
  # Проверять и уведомлять если найдены обновления?
  check: true
  # Скачивать обновления автоматически, если было найдено? (После скачки, сервер - нужно перезапустить!)
  auto-download: false

# Мне стало лень выносить в отдельный конфиг
broadcast:
  # Оставьте пустым, чтобы отключить
  command: "broadcast"
  # Альясы для команды
  aliases: [ "bc", "notify" ]

  # Поддерживаемые плейсхолдеры:
  # {prefix} {player} {suffix} {message}
  format: |-
    &7[&eОБЪЯВЛЕНИЕ&7] &f{message}
    &fОт: &6{player}

  # Указывать в миллисекундах
  cooldown: 30000

  # Форматирование текста.
  # LEGACY - цвет через & и hex &# (Работает только на: 1.16+)
  # LEGACY_ADVANCED - улучшенный аналог legacy с поддержкой &## формата hex (&##123 -> &#112233) (Работает только на: 1.16+)
  # MINIMESSAGE - цвет через <цвет></цвет> (Работает только на: 1.17+)
  # VANILLA - дефолтное форматирование через &
  serializer: LEGACY

  hover:
    # Включение модуля
    enable: false
    # Доступные действия: OPEN_URL, OPEN_FILE, RUN_COMMAND, SUGGEST_COMMAND, CHANGE_PAGE, COPY_TO_CLIPBOARD
    click-action: 'SUGGEST_COMMAND'
    # Команда/ссылка или другое
    click-value: '/m {player} '
    # Само сообщение которое будет показываться при наведении
    text: " &fНаписать &e{player} "

# Настройка команды для отключения персонального чата
# (не отключает бродкасты и авто-сообщения)
disable-own-chat:
  # Оставьте пустым, чтобы отключить
  command: "disablechat"
  # Альясы для команды
  aliases: []

# Настройка команды для отключения авто-сообщений
disable-auto-messages:
  # Оставьте пустым, чтобы отключить
  command: "disableautomessages"
  # Альясы для команды
  aliases: [ "disableam" ]
