# ░██████╗░██╗░██████╗░░█████╗░░█████╗░██╗░░██╗░█████╗░████████╗
# ██╔════╝░██║██╔════╝░██╔══██╗██╔══██╗██║░░██║██╔══██╗╚══██╔══╝
# ██║░░██╗░██║██║░░██╗░███████║██║░░╚═╝███████║███████║░░░██║░░░
# ██║░░╚██╗██║██║░░╚██╗██╔══██║██║░░██╗██╔══██║██╔══██║░░░██║░░░
# ╚██████╔╝██║╚██████╔╝██║░░██║╚█████╔╝██║░░██║██║░░██║░░░██║░░░
# ░╚═════╝░╚═╝░╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░
#
# /gigachat help - чтобы увидеть все доступные команды
#

# Настройка авто-абновлений
updates:
  # Проверять и уведомлять если найдены обновления?
  check: true
  # Скачивать обновления автоматически, если было найдено? (После скачки, сервер - нужно перезапустить!)
  auto-download: false

# Настройка команды для отключения персонального чата
# (не отключает бродкасты и авто-сообщения)
disable-own-chat:
  # Оставьте пустым, чтобы отключить
  command: "disablechat"
  # Альясы для команды
  aliases: []

# Настройка команды для отключения авто-сообщений
disable-auto-messages:
  # Оставьте пустым, чтобы отключить
  command: "disableam"
  # Альясы для команды
  aliases: [ "disableautomessages" ]
