# ███╗░░░███╗██╗░░░██╗░█████╗░██╗░░██╗░█████╗░████████╗
# ████╗░████║╚██╗░██╔╝██╔══██╗██║░░██║██╔══██╗╚══██╔══╝
# ██╔████╔██║░╚████╔╝░██║░░╚═╝███████║███████║░░░██║░░░
# ██║╚██╔╝██║░░╚██╔╝░░██║░░██╗██╔══██║██╔══██║░░░██║░░░
# ██║░╚═╝░██║░░░██║░░░╚█████╔╝██║░░██║██║░░██║░░░██║░░░
# ╚═╝░░░░░╚═╝░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░
#
# Команды плагина:
# /mychat - перезагрузить плагин (Право для использования: mychat.reload)
# /msg <ник> <сообщение> - написать личное сообщение игроку (Право для использования: mychat.privatemessage)
# /ignore <ник> - включить/отключить личные сообщения от игрока (Право для использования: mychat.ignore)
# /socialspy - включить/отключить режим слежки (Право для использования: mychat.socialspy)
#
# Плейсхолдеры для формата сообщений в чатах:
# {player} - ник игрока
# {prefix} - префикс игрока (берется из vault api)
# {suffix} - суффикс игрока (берется из vault api)
# {local-color}, {global-color} - цвет по группе из "groupColors"

# Настройки локального чата
local:
  # Формат сообщений
  format: "&aⓁ&f {prefix}{player}{suffix} &7: {local-color}{message}"
  # Дистанция на которой будет отображаться сообщение
  distance: 100
  # Задержка на чат (указывать в миллисекундах)
  cooldown: 500

# Настройки глобального чата
global:
  # Формат сообщений
  format: "&6Ⓖ&f {prefix}{player}{suffix} &7: {global-color}{message}"
  # Символ который нужно писать для использования глоб. чата (ПИСАТЬ 1 СИМВОЛ И НЕ БОЛЬШЕ!)
  symbol: '!'
  # Нужно ли использовать глобальный чат как основной?
  force: false
  # Задержка на чат (указывать в миллисекундах
  cooldown: 500

# Настройка цветов групп для внутренних плейсхолдеров
groupColors:
  # {local-color}
  local:
    default: "&7"
    admin: "&f&l"
  # {global-color}
  global:
    default: "&7"
    admin: "&f&l"

# Настройка ховер-текста (текст при наведении на сообщение игрока)
# При включении заменяет логику работы чата, что может сказаться на работе других плагинов, включающих в себя его форматирование.
hoverText:
  # Включение модуля
  enable: false
  # Доступные действия: OPEN_URL, OPEN_FILE, RUN_COMMAND, SUGGEST_COMMAND, CHANGE_PAGE, COPY_TO_CLIPBOARD
  click-action: 'SUGGEST_COMMAND'
  # Команда/ссылка или другое
  click-value: '/m {player} '
  # Само сообщение которое будет показываться при наведении
  format: |-
    &fИнформация об игроке {player}
    &fРанг: &6%vault_group%
    &fХП: &6%player_health%
    &fОпыт: &6%player_exp%

# Настройка блокировки чата для новичков
newbieChat:
  # Включение модуля
  enable: true
  # Сколько игрокам нужно отыграть, чтобы смочь писать в чат (В секундах)
  cooldown: 600
  # Сообщение когда чат заблокирован
  denyMessage: "&c[★] &6Подожди! Что-бы написать в чат вы должны отыграть 10 минут на сервере, осталось &c%time%"

newbieCommands:
  # Включение модуля
  enable: true
  # Сколько игрокам нужно отыграть, чтобы смочь писать в чат (В секундах)
  cooldown: 600
  # Сообщение когда чат заблокирован
  denyMessage: "&c[★] &6Подожди! Что-бы написать данную команды вы должны отыграть 10 минут на сервере, осталось &c%time%"
  # Команды, которые будут попадать под newbieCommands
  blockedCommands:
    - "/m"
    - "/pm"
    - "/msg"
    - "/t"
    - "/tell"
    - "/w"
    - "/whisper"

# Настройка авто-сообщений
autoMessage:
  # Включение модуля
  enable: true
  # Выбирать сообщение для отправки из списка наугад?
  random: true
  # Промежуток между отправкой сообщений (В секундах)
  send-interval: 300
  # Сами сообщения:
  messages:
    # Название ни на что, не влияет!
    mychat:
      - "[MyChat] Server is using MyChat 1.1"
    overwrite:
      - "[MyChat] This plugin was mady by OverwriteMC and edited by Groundbreaking"
    monkey:
      - "[MyChat] Overwrite is monkey"

# Настройка приватных сообщений
privateMessages:
  # Команда для отправки приватного сообщения
  pm-command: "msg"
  # Альясы для команды
  pm-aliases:
    - "m"
    - "pm"
    - "w"

  # Команда для игнорирования игрока
  ignore-command: "ignore"
  # Альясы для команды
  ignore-aliases: []

  # Команда для ответа последнему отправившему личное сообщение
  reply-command: "reply"
  # Альясы для команды
  reply-aliases:
    - "r"

  # Команда для просмотра отправки всех личных сообщений
  socialspy-command: "socialspy"
  # Альясы для команды
  socialspy-aliases:
    - "spy"

  print-to-console: true

  # Сообщение, которое увидит игрок использовавший /msg <ник>
  sender-format: "&d[ЛС] &f[&dя &f-> {to-prefix}{to-name}&f] &r{message}"
  # Сообщение, которое увидит получивший игрок
  recipient-format: "&d[ЛС] &f[{from-prefix}{from-name} &f-> &dмне&f] &r{message}"

  # Сообщение, которое увидит игрок прослушивающий сообщения (Написавший /socialspy)
  socialspy-format: "&6* &f[&r{sender_prefix}{sender}{sender_suffix} &f-> &r{target_prefix}{target}{target_suffix}&f] &r{message}"
  console-format: "&f[&r{sender_prefix}{sender}{sender_suffix} &f-> &r{target_prefix}{target}{target_suffix}&f] &r{message}"

  # Звук, который проиграется получателю личного сообщения (Формат: звук;громкость;высота (громкость и высота - необязательны))
  # Оставь "disabled", чтобы отключить
  sound: block_brewing_stand_brew;1.0;1.0

messages:
  # Использовать ли формат <color></color> для сообщений?
  use-minimessage: false
  player-only: "&cДанная команда доступна только игрокам!"
  no-perm: "&cУ вас нет прав на использование данной команды!"
  # {time} - время перезагрузки
  reload: "&aПлагин был успешно перезагружен за {time}мс!"
  player-not-found: "&cУказанный игрок не найден!"
  # {time} - время до окончания задержки
  cooldown-message: "&e[♻]&f Вы слишком быстро пишите! Подождите еще {time}."
  pm-usage-error: "&cВы неправильно ввели команду! Используйте: /msg <ник> <сообщение>"
  cannot-pm-self: "&cВы не можете отправить сообщение самому себе!"
  cannot-ignore-self: "&cВы не можете игнорировать самого себя!"
  recipient-ignores-sender: "&cЭтот игрок игнорирует вас!"
  sender-ignores-recipient: "&cВы не можете написать игроку которого игнорируете!"
  socialspy-enabled: "&aТеперь вы прослушиваете личные сообщения!"
  socialspy-disabled: "&aВы больше не прослушиваете личные сообщения!"
  socialspy-usage-error: "&cВы неправильно ввели команду! Используйте: /socialspy"
  # {player} - ник указанного игрока
  ignore-enabled: "&cВы больше не будете получать сообщения от {player}."
  # {player} - ник указанного игрока
  ignore-disabled: "&cТеперь вы получаете сообщения от {player}."
  ignore-usage-error: "&cВы неправильно ввели команду! Используйте: /ignore <ник>"
  reply-usage-error: "&cВы неправильно ввели команду! Используйте: /reply <сообщение>"

  time:
    hours: "ч. "
    minutes: "м. "
    seconds: "с."