name: GigaChat
version: ${project.version}
main: groundbreaking.gigachat.GigaChat
api-version: 1.13
depend: [ PlaceholderAPI, Vault, LuckPerms ]
softdepend: [ Essentials, CMI, SuperVanish ]
authors: [ Groundbreaking, OverwriteMC ]

libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8

commands:
  gigachat:
    aliases: [ "gc", "gchat" ]

permissions:
  gigachat.adminhover:
    default: op

  gigachat.hex:
    default: op

  gigachat.bypass.cooldown.local:
    default: op

  gigachat.bypass.cooldown.global:
    default: op

  gigachat.bypass.cooldown.socialspy:
    default: op

  gigachat.bypass.cooldown.broadcast:
    default: op

  gigachat.bypass.cooldown.ignore:
    default: op

  gigachat.bypass.cooldown.pm:
    default: op

  gigachat.bypass.chatnewbie:
    default: op

  gigachat.bypass.commandsnewbie:
    default: op

  gigachat.bypass.clearchat:
    default: op

  gigachat.bypass.disabledchat:
    default: op

  gigachat.command.pm:
    default: op

  gigachat.command.ignore:
    default: op

  gigachat.command.socialspy:
    default: op

  gigachat.command.reply:
    default: op

  gigachat.command.setpmsound:
    default: op

  gigachat.command.disablechat:
    default: op

  gigachat.command.clearchat:
    default: op

  gigachat.command.localspy:
    default: op

  gigachat.command.broadcast:
    default: op

  gigachat.automessages:
    default: op

  gigachat.private.color.black:
    default: op
    children:
      gigachat.private.color.0: true

  gigachat.private.color.dark_blue:
    default: op
    children:
      gigachat.private.color.1: true

  gigachat.private.color.dark_green:
    default: op
    children:
      gigachat.private.color.2: true

  gigachat.private.color.dark_aqua:
    default: op
    children:
      gigachat.private.color.3: true

  gigachat.private.color.dark_red:
    default: op
    children:
      gigachat.private.color.4: true

  gigachat.private.color.dark_purple:
    default: op
    children:
      gigachat.private.color.5: true

  gigachat.private.color.gold:
    default: op
    children:
      gigachat.private.color.6: true

  gigachat.private.color.gray:
    default: op
    children:
      gigachat.private.color.7: true

  gigachat.private.color.dark_gray:
    default: op
    children:
      gigachat.private.color.8: true

  gigachat.private.color.blue:
    default: op
    children:
      gigachat.private.color.9: true

  gigachat.private.color.green:
    default: op
    children:
      gigachat.private.color.a: true

  gigachat.private.color.aqua:
    default: op
    children:
      gigachat.private.color.b: true

  gigachat.private.color.red:
    default: op
    children:
      gigachat.private.color.c: true

  gigachat.private.color.light_purple:
    default: op
    children:
      gigachat.private.color.d: true

  gigachat.private.color.yellow:
    default: op
    children:
      gigachat.private.color.e: true

  gigachat.private.color.white:
    default: op
    children:
      gigachat.private.color.f: true

  gigachat.private.style.obfuscated:
    default: op
    children:
      gigachat.private.style.k: true

  gigachat.private.style.bold:
    default: op
    children:
      gigachat.private.style.b: true

  gigachat.private.style.strikethrough:
    default: op
    children:
      gigachat.private.style.m: true

  gigachat.private.style.underline:
    default: op
    children:
      gigachat.private.style.n: true

  gigachat.private.style.italic:
    default: op
    children:
      gigachat.private.style.o: true

  gigachat.private.style.reset:
    default: op
    children:
      gigachat.private.style.r: true

  gigachat.chat.color.black:
    default: op
    children:
      gigachat.chat.color.0: true

  gigachat.chat.color.dark_blue:
    default: op
    children:
      gigachat.chat.color.1: true

  gigachat.chat.color.dark_green:
    default: op
    children:
      gigachat.chat.color.2: true

  gigachat.chat.color.dark_aqua:
    default: op
    children:
      gigachat.chat.color.3: true

  gigachat.chat.color.dark_red:
    default: op
    children:
      gigachat.chat.color.4: true

  gigachat.chat.color.dark_purple:
    default: op
    children:
      gigachat.chat.color.5: true

  gigachat.chat.color.gold:
    default: op
    children:
      gigachat.chat.color.6: true

  gigachat.chat.color.gray:
    default: op
    children:
      gigachat.chat.color.7: true

  gigachat.chat.color.dark_gray:
    default: op
    children:
      gigachat.chat.color.8: true

  gigachat.chat.color.blue:
    default: op
    children:
      gigachat.chat.color.9: true

  gigachat.chat.color.green:
    default: op
    children:
      gigachat.chat.color.a: true

  gigachat.chat.color.aqua:
    default: op
    children:
      gigachat.chat.color.b: true

  gigachat.chat.color.red:
    default: op
    children:
      gigachat.chat.color.c: true

  gigachat.chat.color.light_purple:
    default: op
    children:
      gigachat.chat.color.d: true

  gigachat.chat.color.yellow:
    default: op
    children:
      gigachat.chat.color.e: true

  gigachat.chat.color.white:
    default: op
    children:
      gigachat.chat.color.f: true

  gigachat.chat.style.obfuscated:
    default: op
    children:
      gigachat.chat.style.k: true

  gigachat.chat.style.bold:
    default: op
    children:
      gigachat.chat.style.b: true

  gigachat.chat.style.strikethrough:
    default: op
    children:
      gigachat.chat.style.m: true

  gigachat.chat.style.underline:
    default: op
    children:
      gigachat.chat.style.n: true

  gigachat.chat.style.italic:
    default: op
    children:
      gigachat.chat.style.o: true

  gigachat.chat.style.reset:
    default: op
    children:
      gigachat.chat.style.r: true