name: MyChat
version: ${project.version}
main: groundbreaking.mychat.MyChat
api-version: 1.13
folia-supported:
depend: [ PlaceholderAPI, Vault, LuckPerms ]
authors: [ Groundbreaking, OverwriteMC ]

commands:
  mychat:
    aliases: [ mychat ]

permissions:
  mychat.color.black:
    default: op

  mychat.color.dark_blue:
    default: op

  mychat.color.dark_green:
    default: op

  mychat.color.dark_aqua:
    default: op

  mychat.color.dark_red:
    default: op

  mychat.color.dark_purple:
    default: op

  mychat.color.gold:
    default: op

  mychat.color.gray:
    default: op

  mychat.color.dark_gray:
    default: op

  mychat.color.blue:
    default: op

  mychat.color.green:
    default: op

  mychat.color.aqua:
    default: op

  mychat.color.red:
    default: op

  mychat.color.light_purple:
    default: op

  mychat.color.yellow:
    default: op

  mychat.color.white:
    default: op
  
  mychat.style.obfuscated:
    default: op

  mychat.style.bold:
    default: op

  mychat.style.strikethrough:
    default: op

  mychat.style.underline:
    default: op

  mychat.style.italic:
    default: op

  mychat.style.reset:
    default: op

  mychat.style.hex:
    default: op

  mychat.bypass.cooldown:
    default: op

  mychat.bypass.newbie.chat:
    default: op

  mychat.bypass.newbie.commands:
    default: op

  mychat.automessages:
    default: op