name: ${name}
version: ${project.version}
description: ${description}

main: com.github.groundbreakingmc.gigachat.GigaChat
api-version: 1.13

depend: [ PlaceholderAPI, Vault, LuckPerms ]
softdepend: [ Essentials, CMI, SuperVanish ]

authors: [ Groundbreaking, OverwriteMC ]
website: ${site}

libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - com.zaxxer:HikariCP:5.1.0

commands:
  gigachat:
    aliases: [ "gc", "gchat" ]

permissions:
  gigachat.bypass.validator.chat.chars:
    default: false

  gigachat.bypass.validator.chat.caps:
    default: false

  gigachat.bypass.validator.chat.words:
    default: false

  gigachat.bypass.validator.pm.chars:
    default: false

  gigachat.bypass.validator.pm.caps:
    default: false

  gigachat.bypass.validator.pm.words:
    default: false

  gigachat.adminhover:
    default: false

  gigachat.hex:
    default: false

  gigachat.bypass.cooldown.socialspy:
    default: false

  gigachat.bypass.cooldown.broadcast:
    default: false

  gigachat.bypass.cooldown.ignore:
    default: false

  gigachat.bypass.cooldown.pm:
    default: false

  gigachat.bypass.chatnewbie:
    default: false

  gigachat.bypass.commandsnewbie:
    default: false

  gigachat.bypass.clearchat:
    default: false

  gigachat.bypass.disabledchat:
    default: false

  gigachat.bypass.ignore.private:
    default: false

  gigachat.command.pm:
    default: false

  gigachat.command.ignore.chat:
    default: false

  gigachat.command.ignore.private:
    default: false

  gigachat.command.socialspy:
    default: false

  gigachat.command.reply:
    default: false

  gigachat.command.setpmsound:
    default: false

  gigachat.command.disableam.own:
    default: false

  gigachat.command.disableam.other:
    default: false

  gigachat.command.disablechat:
    default: false

  gigachat.command.disableownchat:
    default: false

  gigachat.command.clearchat:
    default: false

  gigachat.command.spy.other:
    default: false

  gigachat.command.broadcast:
    default: false

  gigachat.color.chat.hex:
    default: false

  gigachat.color.private.hex:
    default: false

  gigachat.color.private.black:
    default: false
    children:
      gigachat.color.private.0: true

  gigachat.color.private.dark_blue:
    default: false
    children:
      gigachat.color.private.1: true

  gigachat.color.private.dark_green:
    default: false
    children:
      gigachat.color.private.2: true

  gigachat.color.private.dark_aqua:
    default: false
    children:
      gigachat.color.private.3: true

  gigachat.color.private.dark_red:
    default: false
    children:
      gigachat.color.private.4: true

  gigachat.color.private.dark_purple:
    default: false
    children:
      gigachat.color.private.5: true

  gigachat.color.private.gold:
    default: false
    children:
      gigachat.color.private.6: true

  gigachat.color.private.gray:
    default: false
    children:
      gigachat.color.private.7: true

  gigachat.color.private.dark_gray:
    default: false
    children:
      gigachat.color.private.8: true

  gigachat.color.private.blue:
    default: false
    children:
      gigachat.color.private.9: true

  gigachat.color.private.green:
    default: false
    children:
      gigachat.color.private.a: true

  gigachat.color.private.aqua:
    default: false
    children:
      gigachat.color.private.b: true

  gigachat.color.private.red:
    default: false
    children:
      gigachat.color.private.c: true

  gigachat.color.private.light_purple:
    default: false
    children:
      gigachat.color.private.d: true

  gigachat.color.private.yellow:
    default: false
    children:
      gigachat.color.private.e: true

  gigachat.color.private.white:
    default: false
    children:
      gigachat.color.private.f: true

  gigachat.style.private.obfuscated:
    default: false
    children:
      gigachat.style.private.k: true

  gigachat.style.private.bold:
    default: false
    children:
      gigachat.style.private.b: true

  gigachat.style.private.strikethrough:
    default: false
    children:
      gigachat.style.private.m: true

  gigachat.style.private.underline:
    default: false
    children:
      gigachat.style.private.n: true

  gigachat.style.private.italic:
    default: false
    children:
      gigachat.style.private.o: true

  gigachat.style.private.reset:
    default: false
    children:
      gigachat.style.private.r: true

  gigachat.color.chat.black:
    default: false
    children:
      gigachat.color.chat.0: true

  gigachat.color.chat.dark_blue:
    default: false
    children:
      gigachat.color.chat.1: true

  gigachat.color.chat.dark_green:
    default: false
    children:
      gigachat.color.chat.2: true

  gigachat.color.chat.dark_aqua:
    default: false
    children:
      gigachat.color.chat.3: true

  gigachat.color.chat.dark_red:
    default: false
    children:
      gigachat.color.chat.4: true

  gigachat.color.chat.dark_purple:
    default: false
    children:
      gigachat.color.chat.5: true

  gigachat.color.chat.gold:
    default: false
    children:
      gigachat.color.chat.6: true

  gigachat.color.chat.gray:
    default: false
    children:
      gigachat.color.chat.7: true

  gigachat.color.chat.dark_gray:
    default: false
    children:
      gigachat.color.chat.8: true

  gigachat.color.chat.blue:
    default: false
    children:
      gigachat.color.chat.9: true

  gigachat.color.chat.green:
    default: false
    children:
      gigachat.color.chat.a: true

  gigachat.color.chat.aqua:
    default: false
    children:
      gigachat.color.chat.b: true

  gigachat.color.chat.red:
    default: false
    children:
      gigachat.color.chat.c: true

  gigachat.color.chat.light_purple:
    default: false
    children:
      gigachat.color.chat.d: true

  gigachat.color.chat.yellow:
    default: false
    children:
      gigachat.color.chat.e: true

  gigachat.color.chat.white:
    default: false
    children:
      gigachat.color.chat.f: true

  gigachat.style.chat.obfuscated:
    default: false
    children:
      gigachat.style.chat.k: true

  gigachat.style.chat.bold:
    default: false
    children:
      gigachat.style.chat.l: true

  gigachat.style.chat.strikethrough:
    default: false
    children:
      gigachat.style.chat.m: true

  gigachat.style.chat.underline:
    default: false
    children:
      gigachat.style.chat.n: true

  gigachat.style.chat.italic:
    default: false
    children:
      gigachat.style.chat.o: true

  gigachat.style.chat.reset:
    default: false
    children:
      gigachat.style.chat.r: true
  
  gigachat.color.broadcast.hex:
    default: false

  gigachat.color.broadcast.black:
    default: false
    children:
      gigachat.color.broadcast.0: true

  gigachat.color.broadcast.dark_blue:
    default: false
    children:
      gigachat.color.broadcast.1: true

  gigachat.color.broadcast.dark_green:
    default: false
    children:
      gigachat.color.broadcast.2: true

  gigachat.color.broadcast.dark_aqua:
    default: false
    children:
      gigachat.color.broadcast.3: true

  gigachat.color.broadcast.dark_red:
    default: false
    children:
      gigachat.color.broadcast.4: true

  gigachat.color.broadcast.dark_purple:
    default: false
    children:
      gigachat.color.broadcast.5: true

  gigachat.color.broadcast.gold:
    default: false
    children:
      gigachat.color.broadcast.6: true

  gigachat.color.broadcast.gray:
    default: false
    children:
      gigachat.color.broadcast.7: true

  gigachat.color.broadcast.dark_gray:
    default: false
    children:
      gigachat.color.broadcast.8: true

  gigachat.color.broadcast.blue:
    default: false
    children:
      gigachat.color.broadcast.9: true

  gigachat.color.broadcast.green:
    default: false
    children:
      gigachat.color.broadcast.a: true

  gigachat.color.broadcast.aqua:
    default: false
    children:
      gigachat.color.broadcast.b: true

  gigachat.color.broadcast.red:
    default: false
    children:
      gigachat.color.broadcast.c: true

  gigachat.color.broadcast.light_purple:
    default: false
    children:
      gigachat.color.broadcast.d: true

  gigachat.color.broadcast.yellow:
    default: false
    children:
      gigachat.color.broadcast.e: true

  gigachat.color.broadcast.white:
    default: false
    children:
      gigachat.color.broadcast.f: true

  gigachat.style.broadcast.obfuscated:
    default: false
    children:
      gigachat.style.broadcast.k: true

  gigachat.style.broadcast.bold:
    default: false
    children:
      gigachat.style.broadcast.b: true

  gigachat.style.broadcast.strikethrough:
    default: false
    children:
      gigachat.style.broadcast.m: true

  gigachat.style.broadcast.underline:
    default: false
    children:
      gigachat.style.broadcast.n: true

  gigachat.style.broadcast.italic:
    default: false
    children:
      gigachat.style.broadcast.o: true

  gigachat.style.broadcast.reset:
    default: false
    children:
      gigachat.style.broadcast.r: true