# Формат чатов. Поддерживается PlaceholderAPI
# <player> - ник игрока
# <prefix> - префикс игрока (берется из vault api)
# <suffix> - суффикс игрока (берется из vault api)
# <dph> - плейсхолдер группы
format:
  local: "&aⓁ&f <prefix> &8⋆&f <player>&7:<dph> <message>"
  # Радиус распространения локального чата
  localRadius: 100
  # Если установлено true - весь чат будет глобальным и не будет требовать символа "!"
  forceGlobal: false
  global: "&cⒼ&f <prefix> &8⋆&f <player>&7:<dph> <message>"

local:
  format: "&aⓁ&f <prefix> &8⋆&f <player>&7:<dph> <message>"
  distance: 100
  cooldown: 500

global:
  format: "&cⒼ&f <prefix> &8⋆&f <player>&7:<dph> <message>"
  symbol: '!'
  # Если установлено true - весь чат будет глобальным
  force: false
  cooldown: 500

cooldownMessage: "&e[♻]&f Вы слишком быстро пишите! Подождите еще %time%."

groupColors:
  default: "&7"
  admin: "&f&l"

# Настройка ховертекста (текст при наведении на сообщение игрока)
# При включении заменяет логику работы чата, что может сказаться на работе других плагинов, включающих в себя его форматирование.
# Сообщения будут отправляться игрокам от сервера.
hoverText:
  enable: false
  format: |-
    &fИнформация об игроке <player>
    &fРанг: &6%vault_group%
    &fХП: &6%player_health%
    &fОпыт: &6%player_exp%

# Настройка блокировки чата для новичков
newbieChat:
  # Включен ли newbieChat
  enable: true
  # Кулдаун на чат для новичков в секундах
  cooldown: 600
  # Сообщение для чата для новичков
  denyMessage: "&c[★] &6Подожди! Что-бы написать в чат вы должны отыграть 10 минут на сервере, осталось &c%time%"

newbieCommands:
  # Включен ли newbieCommands
  enable: true
  # Кулдаун на чат для новичков в секундах
  cooldown: 600
  # Сообщение для чата для новичков
  denyMessage: "&c[★] &6Подожди! Что-бы написать данную команды вы должны отыграть 10 минут на сервере, осталось &c%time%"
  # Команды, которые будут попадать под newbieChat
  blockedCommands:
    - "/m"
    - "/pm"
    - "/msg"
    - "/t"
    - "/tell"
    - "/w"
    - "/whisper"


# Настройка автосообщений
# Существует только по тому, что это есть в Chatty.
autoMessage:
  # Включел ли autoMessage
  enable: true
  # Выдавать ли их рандомно
  random: true
  # Промежуток между сообщениями в секундах
  messagesInterval: 300
  # Должны указываться по порядковому номеру. номер: сообщение (необходимо, чтобы в случае не-рандомной выдачи определять порядок)
  messages:
    1:
      - "[PromisedChat] первое авто-сообщение"
    2:
      - "123"
      - "[PromisedChat] второе авто-сообщение"
      - "123"

privateMessages:
  main-command: ""
  command-aliases:
    - ""

  sender-format: "&d[ЛС] &f[&dя &f-> {to-prefix}{to-name}&f] &r{message}"
  recipient-format: "&d[ЛС] &f[{from-prefix}{from-name} &f-> &dмне&f] &r{message}"

  socialspy-format: "&6* &f[&r<sender_prefix><sender><sender_suffix> &f-> &r<target_prefix><target><target_suffix>&f] &r<message>"

  sound: block_brewing_stand_brew;1.0;1.0

messages:
  player-only: ""
  no-perm: ""
  reload: "&aПлагин был успешно перезагружен за %time%мс!"
  player-not-found: ""
  recipient-ignores-sender: ""
  socialspy-enabled: ""
  socialspy-disabled: ""

  time:
    hours: "ч. "
    minutes: "м. "
    seconds: "с."