name: MyChat
version: 1.0
main: groundbreaking.mychat.MyChat
api-version: 1.13
folia-supported: true
depend: [ PlaceholderAPI, Vault, LuckPerms ]
authors: [ Groundbreaking, OverwriteMC ]

commands:
  promisedchat:
    aliases: [ pchat ]

permissions:
  pchat.color.*:
    children:
      pchat.color.black: true
      pchat.color.dark_blue: true
      pchat.color.dark_green: true
      pchat.color.dark_aqua: true
      pchat.color.dark_red: true
      pchat.color.dark_purple: true
      pchat.color.gold: true
      pchat.color.gray: true
      pchat.color.dark_gray: true
      pchat.color.blue: true
      pchat.color.green: true
      pchat.color.aqua: true
      pchat.color.red: true
      pchat.color.light_purple: true
      pchat.color.yellow: true
      pchat.color.white: true

  pchat.style.*:
    children:
      pchat.style.obfuscated: true
      pchat.style.bold: true
      pchat.style.strikethrough: true
      pchat.style.underline: true
      pchat.style.italic: true
      pchat.style.reset: true
      pchat.style.hex: true

  pchat.bypass.*:
    children:
      pchat.bypass.cooldown: true
      pchat.bypass.newbie: true

  pchat.automessage:
    default: true